package com.osrsdailytasks.boss.catalog;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import com.osrsdailytasks.boss.model.BossEfficiencyDefinition;
import com.osrsdailytasks.training.account.EhpProfile;

// Reviewed development-time snapshot of the public WOM EHB rates endpoint.
// Production code uses this compiled data and never contacts WOM.
final class WomEhbSnapshot
{
	static final String SNAPSHOT_VERSION = "2026-08-27";
	static final String SOURCE_TEMPLATE =
		"https://api.wiseoldman.net/v2/efficiency/rates?type={profile}&metric=ehb";

	private static final List<BossEfficiencyDefinition> DEFINITIONS =
		Collections.unmodifiableList(Arrays.asList(
			// SNAPSHOT_ROWS_START
			row(EhpProfile.MAIN, "abyssal_sire", "50"),
			row(EhpProfile.MAIN, "alchemical_hydra", "30"),
			row(EhpProfile.MAIN, "amoxliatl", "85"),
			row(EhpProfile.MAIN, "araxxor", "40"),
			row(EhpProfile.MAIN, "artio", "60"),
			row(EhpProfile.MAIN, "barrows_chests", "22"),
			row(EhpProfile.MAIN, "brutus", "250"),
			row(EhpProfile.MAIN, "bryophyta", "9"),
			row(EhpProfile.MAIN, "callisto", "142"),
			row(EhpProfile.MAIN, "calvarion", "55"),
			row(EhpProfile.MAIN, "cerberus", "65"),
			row(EhpProfile.MAIN, "chambers_of_xeric", "3.5"),
			row(EhpProfile.MAIN, "chambers_of_xeric_challenge_mode", "3"),
			row(EhpProfile.MAIN, "chaos_elemental", "120"),
			row(EhpProfile.MAIN, "chaos_fanatic", "100"),
			row(EhpProfile.MAIN, "commander_zilyana", "60"),
			row(EhpProfile.MAIN, "corporeal_beast", "60"),
			row(EhpProfile.MAIN, "crazy_archaeologist", "75"),
			row(EhpProfile.MAIN, "dagannoth_prime", "105"),
			row(EhpProfile.MAIN, "dagannoth_rex", "105"),
			row(EhpProfile.MAIN, "dagannoth_supreme", "105"),
			row(EhpProfile.MAIN, "deranged_archaeologist", "80"),
			row(EhpProfile.MAIN, "doom_of_mokhaiotl", "20"),
			row(EhpProfile.MAIN, "duke_sucellus", "39"),
			row(EhpProfile.MAIN, "general_graardor", "58"),
			row(EhpProfile.MAIN, "giant_mole", "125"),
			row(EhpProfile.MAIN, "grotesque_guardians", "37"),
			row(EhpProfile.MAIN, "hespori", "60"),
			row(EhpProfile.MAIN, "kalphite_queen", "55"),
			row(EhpProfile.MAIN, "king_black_dragon", "130"),
			row(EhpProfile.MAIN, "kraken", "100"),
			row(EhpProfile.MAIN, "kreearra", "40"),
			row(EhpProfile.MAIN, "kril_tsutsaroth", "65"),
			row(EhpProfile.MAIN, "lunar_chests", "18"),
			row(EhpProfile.MAIN, "mad_angel", "60"),
			row(EhpProfile.MAIN, "maggot_king", "30"),
			row(EhpProfile.MAIN, "mimic", "60"),
			row(EhpProfile.MAIN, "nex", "23.5"),
			row(EhpProfile.MAIN, "nightmare", "14"),
			row(EhpProfile.MAIN, "obor", "12"),
			row(EhpProfile.MAIN, "phantom_muspah", "30"),
			row(EhpProfile.MAIN, "phosanis_nightmare", "9.6"),
			row(EhpProfile.MAIN, "sarachnis", "110"),
			row(EhpProfile.MAIN, "scorpia", "130"),
			row(EhpProfile.MAIN, "scurrius", "70"),
			row(EhpProfile.MAIN, "shellbane_gryphon", "95"),
			row(EhpProfile.MAIN, "skotizo", "45"),
			row(EhpProfile.MAIN, "sol_heredit", "2.7"),
			row(EhpProfile.MAIN, "spindel", "55"),
			row(EhpProfile.MAIN, "the_corrupted_gauntlet", "7.2"),
			row(EhpProfile.MAIN, "the_gauntlet", "10"),
			row(EhpProfile.MAIN, "the_hueycoatl", "20"),
			row(EhpProfile.MAIN, "the_leviathan", "31"),
			row(EhpProfile.MAIN, "the_royal_titans", "55"),
			row(EhpProfile.MAIN, "the_whisperer", "22"),
			row(EhpProfile.MAIN, "theatre_of_blood", "3.2"),
			row(EhpProfile.MAIN, "theatre_of_blood_hard_mode", "3"),
			row(EhpProfile.MAIN, "thermonuclear_smoke_devil", "150"),
			row(EhpProfile.MAIN, "tombs_of_amascut", "3.7"),
			row(EhpProfile.MAIN, "tombs_of_amascut_expert", "3"),
			row(EhpProfile.MAIN, "tzkal_zuk", "1"),
			row(EhpProfile.MAIN, "tztok_jad", "2.5"),
			row(EhpProfile.MAIN, "vardorvis", "39"),
			row(EhpProfile.MAIN, "venenatis", "80"),
			row(EhpProfile.MAIN, "vetion", "50"),
			row(EhpProfile.MAIN, "vorkath", "34"),
			row(EhpProfile.MAIN, "yama", "18"),
			row(EhpProfile.MAIN, "zulrah", "46"),
			row(EhpProfile.IRONMAN, "abyssal_sire", "44"),
			row(EhpProfile.IRONMAN, "alchemical_hydra", "29"),
			row(EhpProfile.IRONMAN, "amoxliatl", "71"),
			row(EhpProfile.IRONMAN, "araxxor", "38"),
			row(EhpProfile.IRONMAN, "artio", "50"),
			row(EhpProfile.IRONMAN, "barrows_chests", "22"),
			row(EhpProfile.IRONMAN, "brutus", "250"),
			row(EhpProfile.IRONMAN, "bryophyta", "9"),
			row(EhpProfile.IRONMAN, "callisto", "142"),
			row(EhpProfile.IRONMAN, "calvarion", "45"),
			row(EhpProfile.IRONMAN, "cerberus", "54"),
			row(EhpProfile.IRONMAN, "chambers_of_xeric", "3.5"),
			row(EhpProfile.IRONMAN, "chambers_of_xeric_challenge_mode", "3"),
			row(EhpProfile.IRONMAN, "chaos_elemental", "48"),
			row(EhpProfile.IRONMAN, "chaos_fanatic", "80"),
			row(EhpProfile.IRONMAN, "commander_zilyana", "30"),
			row(EhpProfile.IRONMAN, "corporeal_beast", "10"),
			row(EhpProfile.IRONMAN, "crazy_archaeologist", "95"),
			row(EhpProfile.IRONMAN, "dagannoth_prime", "100"),
			row(EhpProfile.IRONMAN, "dagannoth_rex", "100"),
			row(EhpProfile.IRONMAN, "dagannoth_supreme", "100"),
			row(EhpProfile.IRONMAN, "deranged_archaeologist", "95"),
			row(EhpProfile.IRONMAN, "doom_of_mokhaiotl", "18"),
			row(EhpProfile.IRONMAN, "duke_sucellus", "37"),
			row(EhpProfile.IRONMAN, "general_graardor", "31"),
			row(EhpProfile.IRONMAN, "giant_mole", "97"),
			row(EhpProfile.IRONMAN, "grotesque_guardians", "34"),
			row(EhpProfile.IRONMAN, "hespori", "50"),
			row(EhpProfile.IRONMAN, "kalphite_queen", "37"),
			row(EhpProfile.IRONMAN, "king_black_dragon", "75"),
			row(EhpProfile.IRONMAN, "kraken", "90"),
			row(EhpProfile.IRONMAN, "kreearra", "30"),
			row(EhpProfile.IRONMAN, "kril_tsutsaroth", "32"),
			row(EhpProfile.IRONMAN, "lunar_chests", "18"),
			row(EhpProfile.IRONMAN, "mad_angel", "60"),
			row(EhpProfile.IRONMAN, "maggot_king", "30"),
			row(EhpProfile.IRONMAN, "mimic", "50"),
			row(EhpProfile.IRONMAN, "nex", "20"),
			row(EhpProfile.IRONMAN, "nightmare", "11"),
			row(EhpProfile.IRONMAN, "obor", "12"),
			row(EhpProfile.IRONMAN, "phantom_muspah", "27"),
			row(EhpProfile.IRONMAN, "phosanis_nightmare", "9.3"),
			row(EhpProfile.IRONMAN, "sarachnis", "67"),
			row(EhpProfile.IRONMAN, "scorpia", "80"),
			row(EhpProfile.IRONMAN, "scurrius", "60"),
			row(EhpProfile.IRONMAN, "shellbane_gryphon", "95"),
			row(EhpProfile.IRONMAN, "skotizo", "38"),
			row(EhpProfile.IRONMAN, "sol_heredit", "2.7"),
			row(EhpProfile.IRONMAN, "spindel", "50"),
			row(EhpProfile.IRONMAN, "the_corrupted_gauntlet", "7.2"),
			row(EhpProfile.IRONMAN, "the_gauntlet", "10"),
			row(EhpProfile.IRONMAN, "the_hueycoatl", "20"),
			row(EhpProfile.IRONMAN, "the_leviathan", "27"),
			row(EhpProfile.IRONMAN, "the_royal_titans", "55"),
			row(EhpProfile.IRONMAN, "the_whisperer", "21"),
			row(EhpProfile.IRONMAN, "theatre_of_blood", "3.2"),
			row(EhpProfile.IRONMAN, "theatre_of_blood_hard_mode", "3"),
			row(EhpProfile.IRONMAN, "thermonuclear_smoke_devil", "100"),
			row(EhpProfile.IRONMAN, "tombs_of_amascut", "3.7"),
			row(EhpProfile.IRONMAN, "tombs_of_amascut_expert", "3"),
			row(EhpProfile.IRONMAN, "tzkal_zuk", "1"),
			row(EhpProfile.IRONMAN, "tztok_jad", "2.2"),
			row(EhpProfile.IRONMAN, "vardorvis", "37"),
			row(EhpProfile.IRONMAN, "venenatis", "80"),
			row(EhpProfile.IRONMAN, "vetion", "39"),
			row(EhpProfile.IRONMAN, "vorkath", "34"),
			row(EhpProfile.IRONMAN, "yama", "18"),
			row(EhpProfile.IRONMAN, "zulrah", "42"),
			row(EhpProfile.ULTIMATE, "abyssal_sire", "38"),
			row(EhpProfile.ULTIMATE, "alchemical_hydra", "28"),
			row(EhpProfile.ULTIMATE, "amoxliatl", "65"),
			row(EhpProfile.ULTIMATE, "araxxor", "35"),
			row(EhpProfile.ULTIMATE, "artio", "42"),
			row(EhpProfile.ULTIMATE, "barrows_chests", "20"),
			row(EhpProfile.ULTIMATE, "brutus", "250"),
			row(EhpProfile.ULTIMATE, "bryophyta", "7"),
			row(EhpProfile.ULTIMATE, "callisto", "45"),
			row(EhpProfile.ULTIMATE, "calvarion", "40"),
			row(EhpProfile.ULTIMATE, "cerberus", "48"),
			row(EhpProfile.ULTIMATE, "chambers_of_xeric", "3"),
			row(EhpProfile.ULTIMATE, "chambers_of_xeric_challenge_mode", "2.5"),
			row(EhpProfile.ULTIMATE, "chaos_elemental", "38"),
			row(EhpProfile.ULTIMATE, "chaos_fanatic", "60"),
			row(EhpProfile.ULTIMATE, "commander_zilyana", "29"),
			row(EhpProfile.ULTIMATE, "corporeal_beast", "7.5"),
			row(EhpProfile.ULTIMATE, "crazy_archaeologist", "62"),
			row(EhpProfile.ULTIMATE, "dagannoth_prime", "85"),
			row(EhpProfile.ULTIMATE, "dagannoth_rex", "85"),
			row(EhpProfile.ULTIMATE, "dagannoth_supreme", "85"),
			row(EhpProfile.ULTIMATE, "deranged_archaeologist", "85"),
			row(EhpProfile.ULTIMATE, "doom_of_mokhaiotl", "16"),
			row(EhpProfile.ULTIMATE, "duke_sucellus", "35"),
			row(EhpProfile.ULTIMATE, "general_graardor", "30"),
			row(EhpProfile.ULTIMATE, "giant_mole", "85"),
			row(EhpProfile.ULTIMATE, "grotesque_guardians", "32"),
			row(EhpProfile.ULTIMATE, "hespori", "30"),
			row(EhpProfile.ULTIMATE, "kalphite_queen", "33"),
			row(EhpProfile.ULTIMATE, "king_black_dragon", "55"),
			row(EhpProfile.ULTIMATE, "kraken", "80"),
			row(EhpProfile.ULTIMATE, "kreearra", "25"),
			row(EhpProfile.ULTIMATE, "kril_tsutsaroth", "28"),
			row(EhpProfile.ULTIMATE, "lunar_chests", "18"),
			row(EhpProfile.ULTIMATE, "mad_angel", "50"),
			row(EhpProfile.ULTIMATE, "maggot_king", "24"),
			row(EhpProfile.ULTIMATE, "mimic", "25"),
			row(EhpProfile.ULTIMATE, "nex", "12"),
			row(EhpProfile.ULTIMATE, "nightmare", "11"),
			row(EhpProfile.ULTIMATE, "obor", "10"),
			row(EhpProfile.ULTIMATE, "phantom_muspah", "25"),
			row(EhpProfile.ULTIMATE, "phosanis_nightmare", "8.5"),
			row(EhpProfile.ULTIMATE, "sarachnis", "65"),
			row(EhpProfile.ULTIMATE, "scorpia", "38"),
			row(EhpProfile.ULTIMATE, "scurrius", "60"),
			row(EhpProfile.ULTIMATE, "shellbane_gryphon", "85"),
			row(EhpProfile.ULTIMATE, "sol_heredit", "2"),
			row(EhpProfile.ULTIMATE, "spindel", "40"),
			row(EhpProfile.ULTIMATE, "the_corrupted_gauntlet", "7.2"),
			row(EhpProfile.ULTIMATE, "the_gauntlet", "10"),
			row(EhpProfile.ULTIMATE, "the_hueycoatl", "20"),
			row(EhpProfile.ULTIMATE, "the_leviathan", "23"),
			row(EhpProfile.ULTIMATE, "the_royal_titans", "55"),
			row(EhpProfile.ULTIMATE, "the_whisperer", "20"),
			row(EhpProfile.ULTIMATE, "theatre_of_blood", "2.9"),
			row(EhpProfile.ULTIMATE, "theatre_of_blood_hard_mode", "2.6"),
			row(EhpProfile.ULTIMATE, "thermonuclear_smoke_devil", "88"),
			row(EhpProfile.ULTIMATE, "tombs_of_amascut", "3"),
			row(EhpProfile.ULTIMATE, "tombs_of_amascut_expert", "2.5"),
			row(EhpProfile.ULTIMATE, "tzkal_zuk", "0.8"),
			row(EhpProfile.ULTIMATE, "tztok_jad", "2"),
			row(EhpProfile.ULTIMATE, "vardorvis", "33"),
			row(EhpProfile.ULTIMATE, "venenatis", "35"),
			row(EhpProfile.ULTIMATE, "vetion", "35"),
			row(EhpProfile.ULTIMATE, "vorkath", "28"),
			row(EhpProfile.ULTIMATE, "yama", "16"),
			row(EhpProfile.ULTIMATE, "zulrah", "36")
			// SNAPSHOT_ROWS_END
		));

	private WomEhbSnapshot()
	{
	}

	static List<BossEfficiencyDefinition> definitions()
	{
		return DEFINITIONS;
	}

	private static BossEfficiencyDefinition row(
		EhpProfile profile,
		String womBossId,
		String rate)
	{
		String profileId = profile.name().toLowerCase(Locale.ENGLISH);
		return new BossEfficiencyDefinition(
			profile,
			womBossId,
			womBossId.toUpperCase(Locale.ENGLISH),
			new BigDecimal(rate),
			SOURCE_TEMPLATE.replace("{profile}", profileId),
			SNAPSHOT_VERSION);
	}
}
